[general]
import = [
  "~/mainfiles/.config/alacritty/themes/koda.toml"
]

[font]
normal = { family = "Maple Mono NF", style = "Semibold" }
bold = { family = "Maple Mono NF", style = "Bold" }
italic = { family = "Maple Mono NF", style = "Bold" }
bold_italic = { family = "Maple Mono NF", style = "Bold" }
size = 8
offset.x = 0
offset.y = 2

[window]
padding = { x = 10, y = 10 }
opacity = 0.97
decorations = "none"
startup_mode = "maximized"

[cursor]
style = "block"
